### ISSUE TITLE
for  function onehotencode().

### ISSUE THREAD

**Issue by MachineGUN001** [kochgroup/intro_pharma_ai#2]
hi, thanks a lot to provide such good materials for learning.
i have a question about setion 13, as mentioned, 
`For the one-hot encoding of the atoms we use the already written function onehotencode().`

but i cannot find the function in other sections. could you please provide more detailed codes for this function?
many thanks,

best,

**Comment by JanoschMenke** [comment]
Hi @MachineGUN001,

thanks for your feedback. 
After reviewing, I agree that the text is confusingly written. We will update the notebooks in the next week. 
For now the file that contains the funtion `onehotencode()` is found here in the utils folder:

https://github.com/kochgroup/intro_pharma_ai/blob/031da4af5575f2afe2aaa880704deaa92d72a03d/utils/onehotencoder.py

We will make sure to highlight in the notebooks where the additional function can be found.

**Comment by JanoschMenke** [comment]
https://github.com/kochgroup/intro_pharma_ai/blob/031da4af5575f2afe2aaa880704deaa92d72a03d/utils/onehotencoder.py#LL1C1-L31C30

**Comment by MachineGUN001** [comment]
> We will make sure to highlight in the notebooks where the additional function can be found

great! thanks for your help. that works for me. please close the issues.
