### ISSUE TITLE
Found some German inside the notebooks

### ISSUE THREAD

**Issue by koronat** [kochgroup/intro_pharma_ai#3]
Hey, very nice notebooks you have.
I enjoyed a lot, but occasionally I find some German inside the English version. I will add the screenshots here, so you would be able to fix it some day:)
Many thanks for your work!
<img width="1328" alt="Screenshot 2023-05-22 at 16 29 40" src="https://github.com/kochgroup/intro_pharma_ai/assets/115711769/2508fe8b-9bea-4809-aa82-331d7f552e7a">

**Comment by koronat** [comment]
<img width="1279" alt="Screenshot 2023-05-22 at 16 57 24" src="https://github.com/kochgroup/intro_pharma_ai/assets/115711769/1bea46bd-ccdf-4a30-a4d4-8c9d0e8a18bd">

**Comment by SamuelHomberg** [comment]
Hi, thanks for brining that to our attention. I have translated the leftover German ([commit](https://github.com/kochgroup/intro_pharma_ai/commit/20ffa96f5729fc7270b999426770012076ab1585)). 

Please let us know if you find anything else :)

**Comment by koronat** [comment]
<img width="1238" alt="Screenshot 2023-05-24 at 20 18 37" src="https://github.com/kochgroup/intro_pharma_ai/assets/115711769/dc79aceb-1a17-4f59-97e4-313d25c1cc65">

**Comment by koronat** [comment]
<img width="1036" alt="Screenshot 2023-05-24 at 20 35 44" src="https://github.com/kochgroup/intro_pharma_ai/assets/115711769/8f2f7020-1a29-47b3-9f85-9aab1a6b46d3">

**Comment by koronat** [comment]
<img width="980" alt="Screenshot 2023-05-24 at 20 39 43" src="https://github.com/kochgroup/intro_pharma_ai/assets/115711769/78dfbe56-5c6c-4cfa-81ff-7bf792b740c9">

**Comment by koronat** [comment]
There is also a typo here, I guess
<img width="1225" alt="Screenshot 2023-05-25 at 13 19 09" src="https://github.com/kochgroup/intro_pharma_ai/assets/115711769/ab51d26d-107d-4d51-a338-9d5f9bfdd0fa">

**Comment by koronat** [comment]
<img width="1260" alt="Screenshot 2023-05-26 at 11 42 51" src="https://github.com/kochgroup/intro_pharma_ai/assets/115711769/cb67c5b1-05fa-49e6-b79a-dadf3f31e96e">

**Comment by JanoschMenke** [comment]
@SamuelHomberg  I saw you fixed all the mentioned German artifacts, shalle we keep the issue open for more German to come?

**Comment by koronat** [comment]
@JanoschMenke Please, keep it open, I have not looked in all the notebooks:)
Will do during the next few weeks, hopefully.

**Comment by koronat** [comment]
<img width="822" alt="Screenshot 2023-06-04 at 19 37 16" src="https://github.com/kochgroup/intro_pharma_ai/assets/115711769/9d879761-5efc-443c-a4ff-7c5b4c1b3f31">

**Comment by koronat** [comment]
I assume this has to be funCtion :)
<img width="1057" alt="Screenshot 2023-06-30 at 15 04 30" src="https://github.com/kochgroup/intro_pharma_ai/assets/115711769/3652d9e7-828e-44a3-8f86-a7d6756e5997">

**Comment by JanoschMenke** [comment]
@koronat  Good catch, updateted the notebook again

**Comment by koronat** [comment]
this is not the link to ENG wikipedia page

<img width="1077" alt="Screenshot 2023-09-19 at 17 51 12" src="https://github.com/kochgroup/intro_pharma_ai/assets/115711769/1a1fba72-7195-416a-aadd-f9d077c7a502">

**Comment by koronat** [comment]
<img width="771" alt="Screenshot 2023-09-20 at 11 51 30" src="https://github.com/kochgroup/intro_pharma_ai/assets/115711769/a0a7779c-10a1-496f-afb9-ee541323d951">

**Comment by koronat** [comment]
[2023 aclendar.pdf](https://github.com/kochgroup/intro_pharma_ai/files/12671110/2023.aclendar.pdf)

**Comment by koronat** [comment]
<img width="1053" alt="Screenshot 2023-09-20 at 11 53 31" src="https://github.com/kochgroup/intro_pharma_ai/assets/115711769/9845e527-b731-4846-a2aa-50f3a1be227c">

**Comment by koronat** [comment]
![Uploading Screenshot 2023-09-21 at 11.14.27.png…]()

**Comment by koronat** [comment]
variable EPOCS is not used, you probably meant to put it in the for-loop statement

<img width="683" alt="Screenshot 2023-09-21 at 11 24 48" src="https://github.com/kochgroup/intro_pharma_ai/assets/115711769/84345929-6338-42a8-a01a-f31aa1df8160">

**Comment by koronat** [comment]
<img width="1277" alt="Screenshot 2023-09-21 at 11 56 29" src="https://github.com/kochgroup/intro_pharma_ai/assets/115711769/150536b2-c6d6-40a3-92f8-9489c770e317">

**Comment by koronat** [comment]
notebook 9

<img width="969" alt="Screenshot 2023-09-21 at 17 05 52" src="https://github.com/kochgroup/intro_pharma_ai/assets/115711769/41db6dba-ba6a-49d1-b2da-474616e89809">

**Comment by koronat** [comment]
notebook 10, image is crashed

<img width="1297" alt="Screenshot 2023-09-21 at 17 20 03" src="https://github.com/kochgroup/intro_pharma_ai/assets/115711769/5ff14d90-3cdc-41f2-82cb-1b55b70fbc1e">

**Comment by koronat** [comment]
notebook 10, commets are in German

<img width="1268" alt="Screenshot 2023-09-21 at 17 29 05" src="https://github.com/kochgroup/intro_pharma_ai/assets/115711769/79a7f6f1-38a4-453c-b875-a0c4cfa7c743">

**Comment by koronat** [comment]
THthis

<img width="1333" alt="Screenshot 2023-09-21 at 17 34 31" src="https://github.com/kochgroup/intro_pharma_ai/assets/115711769/24595f6f-035c-4af4-b26a-4b4f9af9bf9f">

**Comment by koronat** [comment]
loss_funKtion is repeated 10 times

<img width="982" alt="Screenshot 2023-09-21 at 17 50 38" src="https://github.com/kochgroup/intro_pharma_ai/assets/115711769/fc399140-4731-4627-b307-0093db70367f">

**Comment by koronat** [comment]
keeP

<img width="1339" alt="Screenshot 2023-09-21 at 17 52 47" src="https://github.com/kochgroup/intro_pharma_ai/assets/115711769/4fe6e49c-e328-459b-94d3-28c5bae960c2">

**Comment by koronat** [comment]
notebook 10
dAAt set and iNages

<img width="1297" alt="Screenshot 2023-09-21 at 18 24 01" src="https://github.com/kochgroup/intro_pharma_ai/assets/115711769/93967091-94f1-492f-bb36-f76fc5be7d19">

**Comment by koronat** [comment]
notebook 11

<img width="770" alt="Screenshot 2023-09-22 at 11 18 48" src="https://github.com/kochgroup/intro_pharma_ai/assets/115711769/b2b05632-645e-4813-a6a1-a5729ec562bc">

**Comment by Kamiiiinski** [comment]
fixed in 56dbf6f
