### ISSUE TITLE
Dead link to image in Notebook 10 - Transfer Learning (EN & GER)

### ISSUE THREAD

**Issue by SamuelHomberg** [kochgroup/intro_pharma_ai#8]
Dead link: 
[https://pennylane.ai/qml/_images/transfer_learning_general.png](https://pennylane.ai/qml/_images/transfer_learning_general.png)

What exactly was displayed here?

**Comment by JohannesKaminski** [comment]
Fixed in https://github.com/kochgroup/intro_pharma_ai/commit/94ba8070f1699f5df2f58ee2569880f7d1284692 #
